# Generated by Django 3.2.5 on 2021-08-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordResetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=None, verbose_name='شناسه')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
