# Generated by Django 3.2.5 on 2021-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='Name',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت '),
        ),
    ]
