# Generated by Django 3.2.5 on 2021-08-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
