# Generated by Django 3.2.5 on 2021-07-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210724_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='Family',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='Name',
            new_name='name',
        ),
    ]
