# Generated by Django 3.2.5 on 2021-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210724_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='family',
            field=models.CharField(default='0', max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='0', max_length=100, verbose_name='نام'),
        ),
    ]
