# Generated by Django 3.2.5 on 2021-07-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210724_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='name',
        ),
    ]
