# Generated by Django 3.2.5 on 2021-08-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='created_by',
        ),
    ]
