# Generated by Django 3.2.5 on 2021-08-22 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_postmodel_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='writer',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
